# Some Popular NumPy Functions
(There are a lot more than just these!)

In [2]:
import numpy as np

### Standard array vs NumPy array

In [36]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
np_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

#### Difference in output

In [37]:
print(arr)
print(np_arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 1  2  3  4  5  6  7  8  9 10 11]


#### *Note that arr is a list, and np_arr is a NumPy array. These are different!*

### Printing only even numbers in an array

In [6]:
for num in np_arr:
    if (num % 2) == 0:
        print(num, end = " ")

2 4 6 8 

### Creating an array of random values

In [28]:
rand_arr = np.random.randint(low = 2, high = 9, size = (3,3))
print(rand_arr)

[[3 8 5]
 [3 3 5]
 [8 7 2]]


### Print an array from 0 to 10 (by 2's)

In [16]:
arr = np.arange(0, 11, 2)
print(arr)

[ 0  2  4  6  8 10]


#### *Keep in mind that arr is now a NumPy array, and not a standard list. Let's change it back for now.*

In [18]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
np_arr_2 = np.arange(0, 11, 2)
print(np_arr_2)

[ 0  2  4  6  8 10]


### Creating an array from 0 to 10 of equally spaced values

In [24]:
print(np.linspace(0, 5, retstep=True), "\n")

(array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ]), 0.10204081632653061) 



#### *Note that the default size of the array is 50, but this can be changed*

### Finding shape of an array

In [30]:
print(len(arr))
#print(arr.shape, "\n")

print(len(rand_arr))
print(rand_arr.shape, "\n")

9
3
(3, 3) 



### Reshaping an array

In [38]:
np_arr = np_arr.reshape(3, 3)
print(np_arr, "\n")

ValueError: cannot reshape array of size 11 into shape (3,3)

#### *Note that the size must match when reshaping. This function will not work for arr as it is not a NumPy arrayd*

In [32]:
arr = arr.reshape(3, 3)
print(arr, "\n")

AttributeError: 'list' object has no attribute 'reshape'

#### *Let's convert it to a NumPy array to see if it works*

In [39]:
arr = np.array(arr).reshape(3, 3)
print(arr, "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



### Creating an 'x' by 'x' identity matrix

In [44]:
iden_matrix = np.eye(5)
print(iden_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 'x' is the input parameter for the function; in this case, it is 3.