# NumPy Exercises

#### Try out some exercises for NumPy! Once you can do every exercise without looking at older notebooks or online, you will have formed a deep understanding of NumPy for these workshops.

### Import NumPy

In [1]:
import numpy as np

##### If you forgot how to do this, use last week's notebook for reference

## Some review from last time!

### How do you multiply all values in a list by a value?

In [2]:
arr = [1, 2, 3, 4, 5]
arr = [x * 5 for x in arr]
print(arr)

[5, 10, 15, 20, 25]


##### This is known as list comprehension, which is creating and/or manipulating a list within one line. We will be doing these a lot as we move forward!

### How do you do the same for NumPy arrays?

In [6]:
np_arr = np.array([1, 2, 3, 4, 5]) * 5
#np_arr = np_arr * 5
print(np_arr)

[ 5 10 15 20 25]


##### Hint: It's easier than the last one. First, declare a NumPy array. See if you can figure it out!

## Indexing a NumPy array

#### Slicing a NumPy arrray follows this format:

In [13]:
arr = [0, 1, 2, 3, 4, 5]
print(arr[0:6:3])

[0, 3]


arr[start: stop: step]


Leaving any field blank will default to some value depending on the other fields

#### Advanced Indexing

In [15]:
arr = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]]) 
print(arr)
print(arr[[0 ,1 ,2 ],[0 ,0 ,1]])

[[1 2]
 [3 4]
 [5 6]]
[1 3 6]


[0, 1, 2] represents the rows, and [0, 0, 1] represent the columns

### Can you understand the image below?

![title](numpy_indexing.png)

## Exercises

### Create an array of zeros of size 8

In [18]:
np_arr = np.zeros(8)
print(np_arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


##### Hint: The function for this is zero(). Do you remember how to call NumPy functions?

### Create an array of ones of size 5

In [19]:
np_arr = np.ones(5)
print(np_arr)

[1. 1. 1. 1. 1.]


##### Hint: The function is similar to before, try to guess what it is.

### Change each value in the last array to 7

In [22]:
np_arr = np_arr * 7
print(np_arr)

[343. 343. 343. 343. 343.]


##### Hint: How did we multiply a NumPy array earlier?

### Create an array of values from 2 to 16

In [25]:
np_arr_2 = np.arange(2, 17)
print(np_arr_2)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


##### Remember the function from last time? Try to remember it before you look.

### Make an array of even integers from 6 to 30

In [29]:
even_arr = np.arange(6, 31, 2)
print(even_arr)
#OR
even_arr = np.arange(3, 16) * 2
print(even_arr)

[ 6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 6  8 10 12 14 16 18 20 22 24 26 28 30]


##### Hint: The solution is similar to before, with one extra step.

### Create an array from 0 to 3, and reshape it to a 2x2 matrix

In [35]:
np_arr = np.arange(0, 4)
np_arr.reshape(2, 2)

array([[0, 1],
       [2, 3]])

### Create a 5x5 identity matrix

In [38]:
eye_matr = np.eye(5)
print(eye_matr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Generate an array of 10 random numbers

In [44]:
rand_arr = np.random.rand(10)
rand_arr

array([0.5614175 , 0.8852248 , 0.25038483, 0.1760483 , 0.886974  ,
       0.02179399, 0.38348863, 0.93938614, 0.43424568, 0.18091688])

##### Hint: Use the random.randn() function. Remember that shift+tab shows a short summary of a function.

### Create an array of 10 equally spaced values from 0 to 1

In [47]:
eq_arr = np.linspace(0, 1, 10)
eq_arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### Return the value in arr in the 1st row, 2nd column

In [48]:
arr = np.arange(0, 100, 12).reshape(3, 3)
print(arr)

[[ 0 12 24]
 [36 48 60]
 [72 84 96]]


In [49]:
arr[0, 1]

12

### From the last example, print just the first and third column

In [56]:
arr[0:3:1, 0:3:2]

array([[ 0, 24],
       [36, 60],
       [72, 96]])